../../src/rtl/debounce.v
../../src/rtl/edge_detecte.v
../../src/rtl/fnd_encorder.v
../../src/rtl/gen_ex.v
../../src/rtl/rx_price.v
../../src/rtl/rx.v
../../src/rtl/sw.v
../../src/rtl/tx.v
../../src/rtl/top_uart.v
../../testbench/testbench.v